<HomeScreen>

    MDBoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "Demo App"
            right_action_items: [["dots-vertical", lambda x: x]]

        MDBoxLayout:
            # start your code from here
            MDRectangleFlatButton:
                text: "demo button"
                on_press: root.btn_press_test()
            MDRectangleFlatButton:
                text: "stop"


        
