<HomeScreen>

    MDBoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "So Called Engineers"
            right_action_items: [["dots-vertical", lambda x: x]]

        Widget:

        MDRectangleFlatButton:
            text: "start"
        MDRectangleFlatButton:
            text: "stop"

        MDRectangleFlatButton:
            text: "test voice"

        

        MDRectangleFlatButton:
            text: "speak"


        
